# Generated by Django 3.0.2 on 2020-01-31 08:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок заметки')),
                ('content', models.TextField(verbose_name='Текст заметки')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата/время создания заметки')),
                ('chosen', models.BooleanField(db_index=True, verbose_name='Избранная')),
                ('ready_to_pub', models.BooleanField(db_index=True, default=True, verbose_name='Доступна для публикации')),
                ('link_id', models.UUIDField(default=uuid.uuid4, verbose_name='id для доступа по ссылке')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор заметки')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='note.Category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Note',
                'verbose_name_plural': 'Notes',
            },
        ),
    ]
